### ISSUE TITLE
html_clean unable to produce table of contents with more than two levels

### ISSUE THREAD

**Issue by megaraptor1** [juba/rmdformats#109]
I've been running into an issue with the html_clean rmdformat. Specifically, when I try to set up a knitted html to have a table of contents with more than two levels, the format defaults to treating all headings aside from the first level as the same level. Attached is an example of the knitted document showing what I mean.

![rmdformats example](https://user-images.githubusercontent.com/74024763/120724168-3bfac100-c4a1-11eb-916d-0fd0e7dfda88.jpg)

I've tried altering several of the output settings in RStudio when knitting the document, but nothing seems to work. This is the settings I have been using to produce the above picture.

```
output:
  rmdformats::html_clean:
    highlight: haddock
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    number_sections: TRUE
    thumbnails: FALSE
    code_folding: show
    df_print: paged
    DT: datatable
```
