### ISSUE TITLE
chunk name in kable table caption

### ISSUE THREAD

**Issue by pgseye** [juba/rmdformats#114]
Wondering if I am specifying something incorrectly as I get the chunk name in the table caption as in the screen grab attached.

<img width="944" alt="screenshot_532" src="https://user-images.githubusercontent.com/12015304/126238697-b7c8d0a7-f418-46c5-b819-2c663860da1e.png">

YAML header is:
```
output:
  rmdformats::downcute:
    code_folding: hide
    self_contained: true
    use_bookdown: true
    highlight: tango
    fig_caption: true
    fig_height: 7
    fig_width: 10
```

Thank you.
