### ISSUE TITLE
Floating TOC scrolling over logo

### ISSUE THREAD

**Issue by daexto** [juba/rmdformats#144]
Really enjoying using the downcute template!

I followed the advice from an earlier thread to add a logo to the top of the TOC using the following code:

.Sidebar {
  background-image: url('...');
  background-repeat: no-repeat;
  background-position: center top;
  margin-top: 1em;
}
#toc {
  margin-top: 150px;
}

It works well, until the document becomes long enough that the TOC requires scrolling. Once that happens, as you scroll down the TOC it moves up and clashes with the logo. Is there a way for avoid this happening (the TOC is as short as it can possibly be? Thanks in advance!

**Comment by juba** [comment]
Hi, would it be possible for you to share a sample RMarkdown file that includes the issue ?

**Comment by daexto** [comment]
It doesn't seem to let me attach an RMarkdown or HTML file, but here's a screenshot of the output where I've scrolled down on the TOC causing it to cover the logo:

![screenshot](https://user-images.githubusercontent.com/89420090/186704106-144719dd-5b48-435d-bdd3-1c47598cb9cc.png)

**Comment by juba** [comment]
You may try to add an additional CSS rule like this :

```css
.Sidebar .nav {
  overflow-y: auto;
  max-height: calc(100vh - 350px);
}
```

**Comment by daexto** [comment]
Thanks so much for looking into that. That's solved the overflow issue but has added a second scroll bar, so the TOC now has two competing scroll bars (one covering the full height, the other covering the new reduced height). Do you know if there's any way of turning off the original scroll bar as that one doesn't seem necessary now?

**Comment by juba** [comment]
You may try to add an `overflow-y` property  to the `.Sidebar` rule :

```css
.Sidebar {
    background-image: url('...');
    background-repeat: no-repeat;
    background-position: center top;
    margin-top: 1em;
    overflow-y: hidden;
}
```
