### ISSUE TITLE
Lightbox scales too large for browser window

### ISSUE THREAD

**Issue by paullemmens** [juba/rmdformats#39]
I would have expected, based on experiences with other (generic) image galleries and lightboxes, that the lightbox of an Rmarkdown plot would be scaled to fully fit my browser window. That is, unfortunately, not the case (see screenshot below), unless I maximize or full-screen the browser window (which I prefer not to do).

It's never been different from the situation below (even after a fresh install of everything; recently got a new company laptop and had to install everything fresh and it still happened), so it must be something very local to my setup or is it perhaps by design (or otherwise unavoidable).

Can I (locally) fix this by including additional CSS or is this a true bug?

![image](https://user-images.githubusercontent.com/5063702/41717694-cd04b2ee-755a-11e8-801f-c22e5d71a5ed.png)

**Comment by juba** [comment]
If I understand correctly, the problem is that the lightbox height is too much to fully fit on your screen ?

**Comment by paullemmens** [comment]
No, *only* when I go to full-screen (f11) or maximize the window (windows way), then I can see the full plot. If i have my chrome window large, but *not* full screen/maximized, then the lightbox doesn't scale to fit the space that is available in my chrome window, like on the example where I can't see the x-axis label without scrolling.

**Comment by juba** [comment]
Yes, you're right, that's a bug, your image should fit vertically. I'll take a look at it, thanks for reporting.

**Comment by juba** [comment]
I think this should be fixed in the latest development version. If not, don't hesitate to reopen this issue.

Thanks !

**Comment by paullemmens** [comment]
Works, although I would have expected the lightbox to (even) be a bit smaller than the full height of the browser window, but that's nit picking.

**Comment by paullemmens** [comment]
Hmm, in material it works like that (although it requires a bit of scrolling to get the box centered) but in html_clean it goes full height.

Material:
![image](https://user-images.githubusercontent.com/5063702/42076388-3c6f02c2-7b75-11e8-8b57-212dddc1d0f0.png)

html_clean:
![image](https://user-images.githubusercontent.com/5063702/42076862-24b86a54-7b77-11e8-8a71-0a7a0610f7a3.png)

**Comment by paullemmens** [comment]
hmmm with yet another file I'm getting this below, despite that yaml and other assorted options appear to be identical between the two html_clean files that generated the bottom plot in the previous comment and the plot below.

I'll try something more to see if I at least can get it to behave consistently and then again report back.


```
---
title: "Shiftwork: fastest RT from PVT"
author: Paul Lemmens
affiliation: Philips Research
output:
  rmdformats::html_clean:
    number_sections: false
    theme: paper
    highlight: default
    dev: svg
    df_print: kable
    code_folding: hide
    fig_width: 16
    fig_caption: true
    self_contained: true
    lightbox: true
    gallery: true
  pdf_document:
    toc: false
    toc_depth: 2
    number_sections: false
    highlight: default
    dev: pdf
    df_print: kable
    fig_width: 10
    fig_height: 10
---

```{r set-options-read-chunks, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(results = 'markup', echo=TRUE, message=TRUE, warning=TRUE, dpi = 600,
                      fig.asp = 0.618)
options(width=120)
# ...
```

![image](https://user-images.githubusercontent.com/5063702/42077056-e2d291b8-7b77-11e8-9852-44f3c7cd7855.png)
