### ISSUE TITLE
Error in template.yaml files

### ISSUE THREAD

**Issue by mjfrigaard** [juba/rmdformats#42]
rmdformats `template.yaml` issue
======

The `material` and `readthedown` formats were throwing the following error:

```r
Error in (function (file, template, package = NULL, create_dir = "default",  : 
  template.yaml must contain name and description fields
```

# The fix

Navigate to the `template.yaml` file found here (on my Mac): `Macintosh HD⁩/Library⁩/Frameworks⁩/R.framework⁩/Versions⁩/3.5⁩/Resources⁩/library⁩/rmdformats⁩/rmarkdown⁩/templates⁩/material⁩/template.yaml`

And add the following text:

```yaml
name: HTML material template
description: HTML material template
```

After selecting **R Markdown** > **From Template** > **HTML Material** or **HTML readthedown**, name the file, and select the location. 

This produces the following `yaml` header (for `material` format)

```yaml
---
title: "html_material"
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
---
```
