### ISSUE TITLE
Makefile generated by create.doc() overrides html settings inside Rmd document

### ISSUE THREAD

**Issue by gdevenyi** [juba/rmdformats#48]
Hi,

I have the following preamble in an Rmarkdown document:
```
---
title: "Heavy Metal Exposure of Muskrats"
author: "Gabriel A. Devenyi"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    fig_width: 6.5
    fig_height: 4.875
    highlight: kate
    thumbnails: true
    lightbox: true
    gallery: true
---
```

I get a properly themed html_clean document with lightbox popups and thumbnails, however the lightbox popups do not have the "gallery" navigation interface.
