### ISSUE TITLE
Width left and right panel readthedown

### ISSUE THREAD

**Issue by Digital123456** [juba/rmdformats#49]
Hello, 
I'm trying to change the width of the right and left pannel using readthedown.
I tried to add a .css file with the following: 

But it didn't do the trick. 

`.main-container { 
  max-width: 1500px !important; 
}
`
Is it possible? and if yes, how should I do it?

Many thanks !

**Comment by juba** [comment]
Hi,

I did not tested it, but you can try something like this : 

```css
#content {
    max-width: 1500px !important;
    margin-left: 500px !important;
}
#table-of-contents {
    width: 500px !important;
}
```
