### ISSUE TITLE
material: integration of shiny

### ISSUE THREAD

**Issue by MiWebR** [juba/rmdformats#55]
I got some problems with using the material template and embedded shiny applications together. I´m using the material.Rmd example.

When using the usual preamble chunk

```
---
title: "Sample document"
output:
  rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 4
    fig_height: 4
    df_print: kable
---
```
everything works fine:

![image](https://user-images.githubusercontent.com/49305812/55619360-cf88b800-5798-11e9-87f0-91d749c86e8b.png)

 But when I just integrate "runtime: shiny" (even without integrating an actual shiny app)
```
---
title: "Sample document"
output:
  rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 4
    fig_height: 4
    df_print: kable
runtime: shiny
---
```
the design get´s destroyed and the table of content on the left isn´t working anymore:

![image](https://user-images.githubusercontent.com/49305812/55619482-0c54af00-5799-11e9-8100-4cb5a3a46a2d.png)

My session.Info():

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       bookdown_0.9     digest_0.6.18    later_0.8.0      mime_0.6         R6_2.4.0         xtable_1.8-3     magrittr_1.5     evaluate_0.13   
[10] rmdformats_0.3.5 highr_0.7        rstudioapi_0.9.0 promises_1.0.1   miniUI_0.1.1.1   rmarkdown_1.12   tools_3.5.2      questionr_0.7.0  shiny_1.2.0     
[19] httpuv_1.5.0     xfun_0.5         yaml_2.2.0       compiler_3.5.2   htmltools_0.3.6  knitr_1.22
```
