### ISSUE TITLE
How to automatically number figures and refer to it ?

### ISSUE THREAD

**Issue by LehmannN** [juba/rmdformats#60]
Hello, 

I am wondering if there is a particular way to number the figures and to refer to it, when using one of the rmdformats ? I tried several syntax, and could not find any that would work. I am using the material.rmd template. Here is a minimal version of my rmd file:

```
---
params:
    set_title: "NULL"
    output_dir:     './output/'
title: "`r params$set_title`"
output:
    rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 4
    fig_height: 4
    df_print: kable
    fig_caption: yes
    use_bookdown: true
---


```{r knitr_init, echo=FALSE, results="asis", cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print = "75")
opts_chunk$set(echo         = FALSE,
               cache        = FALSE,
               cache.lazy   = FALSE,
               prompt       = FALSE,
               tidy         = FALSE,
               message      = FALSE,
               warning      = FALSE,
               comment      = NA,
               fig.path     = 'images/',
               out.width    = '50%',
               fig.align    = 'center')
opts_knit$set(width = 75)
```

# Figures

```{r img, fig.cap = "An amazing plot"}
library(ggplot2)
ggplot(mtcars, aes(mpg, as.factor(cyl), col = disp)) + geom_point()
```
Figure \@ref(fig:img): let's say something about this amazing plot.
```

To render it, I use a command like this: 
```
Rscript -e "rmarkdown::render(input='$i', \
                              output_dir='$d', \
                              clean=TRUE, \
                              quiet=FALSE, \
                              params=list(set_title='$title', output_dir='$d'))"
```

I also have another remark: with this code, I loose the little button "show or hide code" (usually at at the top right of the html document). Do you know where it may come from ? Thanks for your help !

**Comment by juba** [comment]
I think it's only an indentation problem in your preamble. If your format it like this it seems to work : 

```
output:
  rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 4
    fig_height: 4
    df_print: kable
    fig_caption: yes
    use_bookdown: true
```
