### ISSUE TITLE
not able to overwrite blockquote format with external css file

### ISSUE THREAD

**Issue by iembry** [juba/rmdformats#77]
Hi, I created a .css file to be included with my R Markdown document that enabled me to overwrite the existing blockquote format (italics), but when I rendered the document nothing changed.

I was using the readthedown style.

How can an external .css file be used with your package?

Thank you.

Irucka

**Comment by juba** [comment]
Adding the following to a css file and loading it with the `css` preamble argument seems to work here :

```css
blockquote {
    font-style: normal;
} 
```

**Comment by iembry** [comment]
Hi @juba, below are my yaml front matter and the contents of the .css file:

```
---
title: Some title
subtitle: Subittle
author: Irucka Embry
date: "`r Sys.Date()`"
lang: "en-us"
output:
  rmdformats::readthedown:
  self-contained: true
  css: style.css
link-citations: yes
linkcolor: blue
bibliography: bibs.bibtex
csl: vancouver2.csl
---
```

contents of style.css

```@charset "UTF-8";

blockquote, blockquote p {text-align: left; margin-left: 2%; margin-right: 2%; border: none; padding: 0; font-style: normal; font-size: 100%; font-family: "liberation serif", freeserif, "linux libertine", "Alegreya", Gentium, "Doulos SIL", "Charis SIL", "Nimbus Mono L", "Nimbus Roman No 9 L", freemono, "Liberation Mono", times, palatino, "times new roman", serif;}
```

I just rendered the document and the changes have not been made with regards to the blockquotes.

Thank you.

**Comment by juba** [comment]
Hi,

I think there may be an indentation problem in your preamble. Would it work with the following ?

```yaml
---
title: Some title
subtitle: Subittle
author: Irucka Embry
date: "`r Sys.Date()`"
lang: "en-us"
output:
  rmdformats::readthedown:
    self-contained: true
    css: style.css
link-citations: yes
linkcolor: blue
bibliography: bibs.bibtex
csl: vancouver2.csl
---
```
