### ISSUE TITLE
Author with footnote not displayed correctly readthedown

### ISSUE THREAD

**Issue by albertostefanelli** [juba/rmdformats#92]
Hi, 

Thanks for the amazing package. I've recently run into a problem with readthedown that I've never encounter before. 
When a footnote is inserted in the author YALM, the "space" that the footnote superscript number takes correspond to the entire width of the postamble. This results in line breaks between the author name and the superscript numbers, and consequently, between different authors. 

I attach an image. The first name is without a footnote while the other 3 have a footnote.

<img width="329" alt="Screenshot 2021-01-27 at 11 50 04" src="https://user-images.githubusercontent.com/41782142/105981658-9d93c480-6096-11eb-9614-5fae3c40a844.png">

My YALM is the following 

```
---
title: A course name | Session 1
author: D. Heerwegh^[[Dirk Heerwegh](mailto:dirk.heerwegh@soc.kuleuven.ac.be)], A. Alanya^[[Ahu Alanya](https://www.kuleuven.be/wieiswie/en/person/00081320)], A. Stefanelli^[[Alberto  Stefanelli](https://albertostefanelli.com/)], B. Meuleman^[[B. Meuleman](https://www.kuleuven.be/wieiswie/en/person/00041613)]
# date: "`r Sys.Date()`"
# fontsize: 10pt 
# link-citations: yes
output:
  #pdf_document:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    use_bookdown: true
    fig_width: 12
    fig_height: 8
---
```

**Comment by juba** [comment]
Hi,

And thanks for taking the time to report the issue with a reproducible example. Footnote links rendering should be fixed in the development version, let me know if it is not the case for you.

You may already know it, but you can also use the multiple authors syntax to have a slightly different presentation :

```
---
title: A course name | Session 1
author: 
  - name: D. Heerwegh^[[Dirk Heerwegh](mailto:dirk.heerwegh@soc.kuleuven.ac.be)]
  - name: A. Alanya^[[Ahu Alanya](https://www.kuleuven.be/wieiswie/en/person/00081320)]
  - name: A. Stefanelli^[[Alberto  Stefanelli](https://albertostefanelli.com/)]
  - name: B. Meuleman^[[B. Meuleman](https://www.kuleuven.be/wieiswie/en/person/00041613)]
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    use_bookdown: true
    fig_width: 12
    fig_height: 8
---
```
