### ISSUE TITLE
different fonts sizes in nested lists 

### ISSUE THREAD

**Issue by albertostefanelli** [juba/rmdformats#94]
Hi, 

thanks again for the excelling package. There might be something off with readthedown nested list font size. The lower level font is bigger than the upper level, as shown in the image below. 

<img width="430" alt="Screenshot 2021-02-01 at 14 46 30" src="https://user-images.githubusercontent.com/41782142/106466978-534a8300-649c-11eb-8c54-2368dcf6a5cc.png">

```
---
title:  Structural Equation Modeling | Lab Session 1
author: A. Stefanelli^[[Alberto  Stefanelli](https://albertostefanelli.com/)], A. Alanya^[[Ahu Alanya](https://www.kuleuven.be/wieiswie/en/person/00081320)], B. Meuleman^[[Bart Meuleman](https://www.kuleuven.be/wieiswie/en/person/00041613)]
# date: "`r Sys.Date()`"
# fontsize: 10pt 
bibliography: /Users/serg/Library/Mobile Documents/com\~apple\~CloudDocs/academia/library.bib
# link-citations: yes
output:
  #pdf_document:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    use_bookdown: true
    fig_width: 12
    fig_height: 8
# header-includes
---

# Model diagnostics

Important things to check after running the model:

1. Estimates
    - Did indicator load well on the factors?
2. Model fit
    - Are the fit indices good?
3. Heywood cases/ reasonable solution
    - Are variances positive + r-squared is below 1?`
    - Are there any extreme SEs?

```
 
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stringr_1.4.0         sjPlot_2.8.7          corrplot_0.84         scales_1.1.1          ggplot2_3.3.3        
 [6] lavaan.survey_1.1.3.1 survey_4.0            survival_3.2-7        Matrix_1.2-18         lavaan_0.6-7         
[11] psych_2.0.12          dplyr_1.0.3           haven_2.3.1           tidySEM_0.1.3.1      

loaded via a namespace (and not attached):
  [1] minqa_1.2.4         TH.data_1.0-10      colorspace_2.0-0    ellipsis_0.3.1      rsconnect_0.8.16   
  [6] sjlabelled_1.1.7    rprojroot_2.0.2     estimability_1.3    parameters_0.11.0   fs_1.5.0           
 [11] rstudioapi_0.13     farver_2.0.3        remotes_2.2.0       fansi_0.4.2         mvtnorm_1.1-1      
 [16] codetools_0.2-16    splines_4.0.3       mnormt_2.0.2        knitr_1.30          sjmisc_2.8.6       
 [21] texreg_1.37.5       pkgload_1.1.0       nloptr_1.2.2.2      ggeffects_1.0.1     broom_0.7.3        
 [26] effectsize_0.4.3    readr_1.4.0         compiler_4.0.3      httr_1.4.2          sjstats_0.18.1     
 [31] emmeans_1.5.3       backports_1.2.1     assertthat_0.2.1    cli_2.2.0           htmltools_0.5.1    
 [36] prettyunits_1.1.1   tools_4.0.3         igraph_1.2.6        coda_0.19-4         gtable_0.3.0       
 [41] glue_1.4.2          Rcpp_1.0.6          vctrs_0.3.6         nlme_3.1-149        insight_0.12.0     
 [46] xfun_0.20           ps_1.5.0            proto_1.0.0         testthat_3.0.1      lme4_1.1-26        
 [51] lifecycle_0.2.0     devtools_2.3.2      statmod_1.4.35      MASS_7.3-53         zoo_1.8-8          
 [56] hms_1.0.0           parallel_4.0.3      sandwich_3.0-0      yaml_2.2.1          curl_4.3           
 [61] memoise_1.1.0       pander_0.6.3        stringi_1.5.3       bayestestR_0.8.0    desc_1.2.0         
 [66] boot_1.3-25         pkgbuild_1.2.0      rlang_0.4.10        pkgconfig_2.0.3     evaluate_0.14      
 [71] lattice_0.20-41     purrr_0.3.4         labeling_0.4.2      processx_3.4.5      tidyselect_1.1.0   
 [76] plyr_1.8.6          magrittr_2.0.1      bookdown_0.21       R6_2.5.0            generics_0.1.0     
 [81] multcomp_1.4-15     DBI_1.1.1           gsubfn_0.7          pillar_1.4.7        withr_2.4.0        
 [86] tibble_3.0.5        performance_0.6.1   modelr_0.1.8        crayon_1.3.4        tmvnsim_1.0-2      
 [91] MplusAutomation_0.8 rmarkdown_2.6       usethis_2.0.0       data.table_1.13.6   pbivnorm_0.6.0     
 [96] callr_3.5.1         rmdformats_1.0.2    forcats_0.5.0       digest_0.6.27       xtable_1.8-4       
[101] tidyr_1.1.2         stats4_4.0.3        munsell_0.5.0       mitools_2.4         sessioninfo_1.1.1  
```
