### ISSUE TITLE
readthedown and DT::datatable() - fixing vertical table location w.r.t. pagination and search fields

### ISSUE THREAD

**Issue by heseber** [juba/rmdformats#95]
For `DT::datatable` the pagination and search fields are displayed at the same vertical position as the table itself, and the width of the table is reduced by the width of these two fields.

This can be fixed with css:

```css
.table-wrapper {
  margin-top: 3em;
}
```

By the way, the width of the main sheet can be increased by this:
```css
#content {
  max-width: 1000px;
}
```
