### ISSUE TITLE
Downcute: Add logo?

### ISSUE THREAD

**Issue by tspeidel** [juba/rmdformats#96]
Thanks for another beautiful and modern template!
I want to add a logo, either at the bottom of the TOC or below the author. In the past, I tweaked the readthedown css like so:

`
#table-of-contents {
  background-image: url("logo_107x45.png");
  background-repeat: no-repeat;
  background-position: 50% 86%;
}
`

I'm just wondering how I can do that with downcute as the css looks a lot more complicated.

**Comment by juba** [comment]
Hi,

Here is a way to put it in the sidebar, at the bottom :

```css
.Sidebar {
  background-image: url('...');
  background-repeat: no-repeat;
  background-position: center bottom;
  margin-bottom: 1em;
}
```

Or at the top : 

```
.Sidebar {
  background-image: url('...');
  background-repeat: no-repeat;
  background-position: center top;
  margin-top: 1em;
}
#toc {
  margin-top: 150px;
}
```

If you want to put it below the author, maybe the simplest is to add directly to the top of the content of your document ? Otherwise something like this could do the trick : 

```css
.authors {
  background-image: url('...');
  background-repeat: no-repeat;
  background-position: left bottom;
  height: 220px;
}
```

**Comment by tspeidel** [comment]
Thank you!

**Comment by vidigal88** [comment]
Hi, really nice template thanks.

The solution provided worked only when I add the logo using .authors {} but I would like to add it at the upper right corner.
I'm using robobook.

Any other idea?

Thanks

**Comment by juba** [comment]
For robobook you could add something like the following (not tested, though) : 

```css
.body-inner {
  background-image: url('...');
  background-repeat: no-repeat;
  background-position: top right;
}
```
